import { UsuariosService } from './usuarios.service';
import { CreateUsuarioDto } from './dto/create-usuario.dto';
import { UpdateUsuarioDto } from './dto/update-usuario.dto';
export declare class UsuariosController {
    private readonly usuariosService;
    constructor(usuariosService: UsuariosService);
    create(createUsuarioDto: CreateUsuarioDto, req: any): Promise<{
        usuario_id: number;
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        googleId: string | null;
        correo: string | null;
        rol_id: number;
        estado: string;
        comercio_id: number | null;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }>;
    findAll(req: any): Promise<{
        comercio: {
            nombre: string;
            estado: string;
            comercio_id: number;
            creado_en: Date;
            direccion: string | null;
            telefono: string | null;
            email: string | null;
            activo: boolean;
            categoria: string | null;
            logo_url: string | null;
            dueno_nombre: string | null;
            dueno_apellido: string | null;
            dueno_email: string | null;
            dueno_telefono: string | null;
            fecha_solicitud: Date;
            fecha_activacion: Date | null;
            fecha_suspension: Date | null;
            motivo_suspension: string | null;
            actualizado_en: Date;
        } | null;
        rol: {
            nombre: string;
            rol_id: number;
        };
        usuario_id: number;
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        googleId: string | null;
        correo: string | null;
        rol_id: number;
        estado: string;
        comercio_id: number | null;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }[]>;
    findOne(id: number, req: any): Promise<{
        comercio: {
            nombre: string;
            estado: string;
            comercio_id: number;
            creado_en: Date;
            direccion: string | null;
            telefono: string | null;
            email: string | null;
            activo: boolean;
            categoria: string | null;
            logo_url: string | null;
            dueno_nombre: string | null;
            dueno_apellido: string | null;
            dueno_email: string | null;
            dueno_telefono: string | null;
            fecha_solicitud: Date;
            fecha_activacion: Date | null;
            fecha_suspension: Date | null;
            motivo_suspension: string | null;
            actualizado_en: Date;
        } | null;
        rol: {
            nombre: string;
            rol_id: number;
        };
        usuario_id: number;
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        googleId: string | null;
        correo: string | null;
        rol_id: number;
        estado: string;
        comercio_id: number | null;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    } | null>;
    update(id: number, updateUsuarioDto: UpdateUsuarioDto, req: any): Promise<{
        comercio: {
            nombre: string;
            estado: string;
            comercio_id: number;
            creado_en: Date;
            direccion: string | null;
            telefono: string | null;
            email: string | null;
            activo: boolean;
            categoria: string | null;
            logo_url: string | null;
            dueno_nombre: string | null;
            dueno_apellido: string | null;
            dueno_email: string | null;
            dueno_telefono: string | null;
            fecha_solicitud: Date;
            fecha_activacion: Date | null;
            fecha_suspension: Date | null;
            motivo_suspension: string | null;
            actualizado_en: Date;
        } | null;
        rol: {
            nombre: string;
            rol_id: number;
        };
        usuario_id: number;
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        googleId: string | null;
        correo: string | null;
        rol_id: number;
        estado: string;
        comercio_id: number | null;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }>;
    remove(id: number, req: any): Promise<{
        pass: string | null;
        usuario_id: number;
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        googleId: string | null;
        correo: string | null;
        rol_id: number;
        estado: string;
        comercio_id: number | null;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }>;
}
