import { CreateUsuarioDto } from './dto/create-usuario.dto';
import { UpdateUsuarioDto } from './dto/update-usuario.dto';
import { PrismaService } from 'src/prisma/prisma.service';
export declare class UsuariosService {
    private prisma;
    constructor(prisma: PrismaService);
    create(createUsuarioDto: CreateUsuarioDto): Promise<{
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        correo: string | null;
        rol_id: number;
        comercio_id: number | null;
        usuario_id: number;
        googleId: string | null;
        estado: string;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }>;
    findAll(): Promise<{
        comercio: {
            nombre: string;
            comercio_id: number;
            estado: string;
            creado_en: Date;
            direccion: string | null;
            telefono: string | null;
            email: string | null;
            activo: boolean;
            categoria: string | null;
            logo_url: string | null;
            dueno_nombre: string | null;
            dueno_apellido: string | null;
            dueno_email: string | null;
            dueno_telefono: string | null;
            fecha_solicitud: Date;
            fecha_activacion: Date | null;
            fecha_suspension: Date | null;
            motivo_suspension: string | null;
            actualizado_en: Date;
        } | null;
        rol: {
            nombre: string;
            rol_id: number;
        };
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        correo: string | null;
        rol_id: number;
        comercio_id: number | null;
        usuario_id: number;
        googleId: string | null;
        estado: string;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }[]>;
    findAllByComercio(comercio_id: number): Promise<{
        comercio: {
            nombre: string;
            comercio_id: number;
            estado: string;
            creado_en: Date;
            direccion: string | null;
            telefono: string | null;
            email: string | null;
            activo: boolean;
            categoria: string | null;
            logo_url: string | null;
            dueno_nombre: string | null;
            dueno_apellido: string | null;
            dueno_email: string | null;
            dueno_telefono: string | null;
            fecha_solicitud: Date;
            fecha_activacion: Date | null;
            fecha_suspension: Date | null;
            motivo_suspension: string | null;
            actualizado_en: Date;
        } | null;
        rol: {
            nombre: string;
            rol_id: number;
        };
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        correo: string | null;
        rol_id: number;
        comercio_id: number | null;
        usuario_id: number;
        googleId: string | null;
        estado: string;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }[]>;
    findOne(id: number): Promise<{
        comercio: {
            nombre: string;
            comercio_id: number;
            estado: string;
            creado_en: Date;
            direccion: string | null;
            telefono: string | null;
            email: string | null;
            activo: boolean;
            categoria: string | null;
            logo_url: string | null;
            dueno_nombre: string | null;
            dueno_apellido: string | null;
            dueno_email: string | null;
            dueno_telefono: string | null;
            fecha_solicitud: Date;
            fecha_activacion: Date | null;
            fecha_suspension: Date | null;
            motivo_suspension: string | null;
            actualizado_en: Date;
        } | null;
        rol: {
            nombre: string;
            rol_id: number;
        };
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        correo: string | null;
        rol_id: number;
        comercio_id: number | null;
        usuario_id: number;
        googleId: string | null;
        estado: string;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    } | null>;
    update(id: number, updateUsuarioDto: UpdateUsuarioDto): Promise<{
        comercio: {
            nombre: string;
            comercio_id: number;
            estado: string;
            creado_en: Date;
            direccion: string | null;
            telefono: string | null;
            email: string | null;
            activo: boolean;
            categoria: string | null;
            logo_url: string | null;
            dueno_nombre: string | null;
            dueno_apellido: string | null;
            dueno_email: string | null;
            dueno_telefono: string | null;
            fecha_solicitud: Date;
            fecha_activacion: Date | null;
            fecha_suspension: Date | null;
            motivo_suspension: string | null;
            actualizado_en: Date;
        } | null;
        rol: {
            nombre: string;
            rol_id: number;
        };
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        correo: string | null;
        rol_id: number;
        comercio_id: number | null;
        usuario_id: number;
        googleId: string | null;
        estado: string;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }>;
    remove(id: number): import("@prisma/client").Prisma.Prisma__UsuarioClient<{
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        pass: string | null;
        correo: string | null;
        rol_id: number;
        comercio_id: number | null;
        usuario_id: number;
        googleId: string | null;
        estado: string;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    findByUsername(username: string): Promise<({
        comercio: {
            nombre: string;
            comercio_id: number;
            estado: string;
            creado_en: Date;
            direccion: string | null;
            telefono: string | null;
            email: string | null;
            activo: boolean;
            categoria: string | null;
            logo_url: string | null;
            dueno_nombre: string | null;
            dueno_apellido: string | null;
            dueno_email: string | null;
            dueno_telefono: string | null;
            fecha_solicitud: Date;
            fecha_activacion: Date | null;
            fecha_suspension: Date | null;
            motivo_suspension: string | null;
            actualizado_en: Date;
        } | null;
        rol: {
            nombre: string;
            rol_id: number;
        };
    } & {
        nombre: string;
        apellido: string;
        dni: string | null;
        user: string | null;
        pass: string | null;
        correo: string | null;
        rol_id: number;
        comercio_id: number | null;
        usuario_id: number;
        googleId: string | null;
        estado: string;
        email_verificado: boolean;
        token_verificacion: string | null;
        creado_en: Date;
    }) | null>;
}
