import { PrismaService } from 'src/prisma/prisma.service';
export declare class ComerciosService {
    private prisma;
    constructor(prisma: PrismaService);
    findAll(): import("@prisma/client").Prisma.PrismaPromise<({
        _count: {
            usuarios: number;
            clientes: number;
            empleados: number;
            servicios: number;
            turnos: number;
        };
    } & {
        nombre: string;
        estado: string;
        comercio_id: number;
        creado_en: Date;
        direccion: string | null;
        telefono: string | null;
        email: string | null;
        activo: boolean;
        categoria: string | null;
        logo_url: string | null;
        dueno_nombre: string | null;
        dueno_apellido: string | null;
        dueno_email: string | null;
        dueno_telefono: string | null;
        fecha_solicitud: Date;
        fecha_activacion: Date | null;
        fecha_suspension: Date | null;
        motivo_suspension: string | null;
        actualizado_en: Date;
    })[]>;
    findOne(id: number): import("@prisma/client").Prisma.Prisma__ComercioClient<({
        usuarios: {
            pass: string | null;
            usuario_id: number;
            nombre: string;
            apellido: string;
            dni: string | null;
            user: string | null;
            googleId: string | null;
            correo: string | null;
            rol_id: number;
            estado: string;
            comercio_id: number | null;
            email_verificado: boolean;
            token_verificacion: string | null;
            creado_en: Date;
        }[];
    } & {
        nombre: string;
        estado: string;
        comercio_id: number;
        creado_en: Date;
        direccion: string | null;
        telefono: string | null;
        email: string | null;
        activo: boolean;
        categoria: string | null;
        logo_url: string | null;
        dueno_nombre: string | null;
        dueno_apellido: string | null;
        dueno_email: string | null;
        dueno_telefono: string | null;
        fecha_solicitud: Date;
        fecha_activacion: Date | null;
        fecha_suspension: Date | null;
        motivo_suspension: string | null;
        actualizado_en: Date;
    }) | null, null, import("@prisma/client/runtime/library").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    create(data: any): import("@prisma/client").Prisma.Prisma__ComercioClient<{
        nombre: string;
        estado: string;
        comercio_id: number;
        creado_en: Date;
        direccion: string | null;
        telefono: string | null;
        email: string | null;
        activo: boolean;
        categoria: string | null;
        logo_url: string | null;
        dueno_nombre: string | null;
        dueno_apellido: string | null;
        dueno_email: string | null;
        dueno_telefono: string | null;
        fecha_solicitud: Date;
        fecha_activacion: Date | null;
        fecha_suspension: Date | null;
        motivo_suspension: string | null;
        actualizado_en: Date;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, import("@prisma/client").Prisma.PrismaClientOptions>;
    update(id: number, data: any): Promise<{
        nombre: string;
        estado: string;
        comercio_id: number;
        creado_en: Date;
        direccion: string | null;
        telefono: string | null;
        email: string | null;
        activo: boolean;
        categoria: string | null;
        logo_url: string | null;
        dueno_nombre: string | null;
        dueno_apellido: string | null;
        dueno_email: string | null;
        dueno_telefono: string | null;
        fecha_solicitud: Date;
        fecha_activacion: Date | null;
        fecha_suspension: Date | null;
        motivo_suspension: string | null;
        actualizado_en: Date;
    }>;
    remove(id: number): Promise<{
        nombre: string;
        estado: string;
        comercio_id: number;
        creado_en: Date;
        direccion: string | null;
        telefono: string | null;
        email: string | null;
        activo: boolean;
        categoria: string | null;
        logo_url: string | null;
        dueno_nombre: string | null;
        dueno_apellido: string | null;
        dueno_email: string | null;
        dueno_telefono: string | null;
        fecha_solicitud: Date;
        fecha_activacion: Date | null;
        fecha_suspension: Date | null;
        motivo_suspension: string | null;
        actualizado_en: Date;
    }>;
}
